apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-generator
  labels:
    helm.sh/chart: event-generator-0.1.1
    app.kubernetes.io/name: "event-generator"
    app.kubernetes.io/instance: "event-generator"
    app.kubernetes.io/part-of: "event-generator"
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: "Helm"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-generator
  labels:
    helm.sh/chart: event-generator-0.1.1
    app.kubernetes.io/name: "event-generator"
    app.kubernetes.io/instance: "event-generator"
    app.kubernetes.io/part-of: "event-generator"
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: "Helm"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - serviceaccounts
  - pods
  verbs:
  - list
  - get
  - create
  - delete
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - list
  - get
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-generator
  labels:
    helm.sh/chart: event-generator-0.1.1
    app.kubernetes.io/name: "event-generator"
    app.kubernetes.io/instance: "event-generator"
    app.kubernetes.io/part-of: "event-generator"
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: "Helm"
subjects:
  - kind: ServiceAccount
    name: event-generator
    namespace: default
roleRef:
  kind: ClusterRole
  name: event-generator
  apiGroup: rbac.authorization.k8s.io
---
